version: '3.8'
services:
    # This app
    app:
        build: .
        ports:
            - 8090:8090
        expose:
            - '8090'
        depends_on:
            - mongo
        restart: always
        environment:
            PORT: 8090
            MONGO_URI: mongodb://mongo:supersecret@mongo:27017
            MONGO_DB: gosocial_db
            GOOGLE_APPLICATION_CREDENTIALS: gcs.json
            GOOGLE_APPLICATION_BUCKET: ct-go-social
            KAFKA_BROKERS: localhost:9093
            KAFKA_CONSUMER_GROUP: group_notify
            KAFKA_TOPIC: like_event
    # MongoDB
    mongo:
        container_name: mongo
        image: mongo:4.0
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: supersecret
            MONGO_INITDB_DATABASE: gosocial_db
        ports:
            - 27017:27017
        expose:
            - '27017'

    # Kafka
    zookeeper:
        container_name: zookeeper
        restart: always
        image: docker.io/bitnami/zookeeper:3.8
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        container_name: kafka
        restart: always
        image: docker.io/bitnami/kafka:3.3
        ports:
            - '9093:9093'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
            - TOPICS="like_event"
        depends_on:
            - zookeeper
